var d3Svg = require('d3-svg')
var d3Bar = require('d3-data')
var d3Bar = require('d3-parse-data')
var d3Bar = require('d3-bar')
var d3Bar = require('d3-pie')
var d3Bar = require('d3-scatter')
var c3 = require('c3')
console.log('req svg, bar, c3 for druid: ' + d3Svg + d3Bar + c3)
